spring:
  application:
    name: cvteques-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cvteques
    username: postgres
  security:
    user:
      name: admin
      password: test
  session:
    jdbc:
      initialize-schema: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  cors:
    allowed:
      origins: "http://localhost:3000"
      methods: "*"
      headers: "*"
      credentials: true
logging:
  level:
    web: DEBUG
    org:
      springframework:
        context:
          config: DEBUG
        security: DEBUG