spring:
  application:
    name: cvteques-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cvteques
    username: postgres
    password: Loumain92
  security:
    user:
      name: admin
      password: test
  session:
    jdbc:
      initialize-schema: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  cors:
    allowed:
      origins: "http://localhost:3000"
      methods: "*"
      headers: "*"
      credentials: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "cvteques.noreply@gmail.com"
    password: "xclo oldb smtn tssi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    web: DEBUG
    org:
      springframework:
        context:
          config: DEBUG
        security: DEBUG