spring:
  application:
    name: cvteques-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cvteques
    username: postgres
  security:
    user:
      name: admin
      password: test
  session:
    jdbc:
      initialize-schema: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  cors:
    allowed:
      origins: "http://localhost:3000"
      methods: "*"
      headers: "*"
      credentials: true
  jwt:
    secret: "3zZbKJ7e8f9gH1i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P5Q6R7S8T9U0V1W2X3Y4Z"
# On fera un application yaml local pour les devs
  mail:
    host: smtp.gmail.com
    port: 587
    username: "cvteques.noreply@gmail.com"
    password: "xclo oldb smtn tssi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: file:./uploads/
logging:
  level:
    web: DEBUG
    org:
      springframework:
        context:
          config: DEBUG
        security: DEBUG